#!/bin/bash
. ~/.dotfilesrc

function pkg
{
  if [ ! `command -v $1` ] ; then
    sudo apt-get install -y $1
  fi
}

# Minimal packages to get work done, like on a remote server
pkg 'joe'
pkg 'vim'
pkg 'lzop'

# Go big or go home in dev mode
if [ "${DOTFILES_DEV}" == "y" ]; then
  pkg 'grip' # for viewing markdown
  pkg 'build-essential'
fi



