#!/bin/bash
. ~/.dotfilesrc

# update if we haven't in more than a day
if [[ $(find "/var/cache/apt/pkgcache.bin" -mtime +1 -print) ]]; then
  sudo apt-get update
fi


function pkg
{
  if [[ ! `dpkg -s $1 | egrep 'Status.+installed'` ]] ; then
    echo "need to install $1"
    sudo apt-get install -y $1
  fi
}

# Minimal packages to get work done, like on a remote server
pkg 'joe'
pkg 'vim'
pkg 'lzop'
pkg 'openssh-server'
pkg 'ncdu'
pkg 'xbindkeys'
pkg 'whois'
pkg 'screen'

# Go big or go home in dev mode
if [ "${DOTFILES_DEV}" == "y" ]; then
  pkg 'grip' # for viewing markdown
  pkg 'build-essential'
  pkg 'libssl-dev'
  pkg 'libreadline-dev'
  pkg 'zlib1g-dev'
  pkg 'exuberant-ctags'
  pkg 'golang-go'
  pkg 'exfat-fuse'
  pkg 'exif'
  pkg 'ansible'
fi
