#!/bin/bash

if [ -e "${HOME}/.rbenv" ]; then
  cd ~/.rbenv && git pull
else
  git clone https://github.com/rbenv/rbenv.git ~/.rbenv
fi

if [ -e "${HOME}/.rbenv/plugins/ruby-build" ]; then
  cd ~/.rbenv/plugins/ruby-build && git pull
else
  git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
fi

function install_ruby(){
  if [[ ! `rbenv versions | grep $1` ]]; then
    rbenv install $1
  fi
}

install_ruby 2.3.4
install_ruby 2.4.1

rbenv global 2.4.1
