#!/bin/bash
set -e # fail fast

# We need these commands to exist in order to proceed.
# See README.md
commands=(git ansible-playbook rcup)
for cmd in "${commands[@]}"; do
  command -v "$cmd" > /dev/null || { echo "ERROR: command not found: ${cmd}" ; exit 1; }
done

# Update dotfiles with rcm.
rcup -v

if [ -f ~/.dotfilesrc ]; then
  # shellcheck disable=SC1090
  . "${HOME}/.dotfilesrc"
else
  echo "ERROR: no ~/.dotfilesrc, run ./setup first"
  exit
fi

# Figure out what ansible playbooks, if any, to run
playbooks=()
# Need to add a flag for this
playbooks+=("provisioning/core.yml")
if [ "${DOTFILES_GUI}" == "y" ]; then
  playbooks+=("provisioning/desktop.yml")
  playbooks+=("provisioning/graphic-design.yml")
fi

if [ "${DOTFILES_DEV}" == "y"  ]; then
  playbooks+=("provisioning/development.yml")
fi

if [ ${#playbooks[@]} -gt 0 ]; then
  PATH=/usr/bin:/bin ansible-playbook --ask-become-pass -e ansible_python_interpreter=/usr/bin/python3 \
    $(IFS=" " ;echo "${playbooks[*]}")
fi

# Install asdf plugins
set +e # This is a bad hack to get around this command failing when all plugins are installed
awk '{print $1}' ~/.tool-versions | xargs -L1 asdf plugin-add
set -e

asdf install
