#!/bin/bash
set -e #fail fast

# We need these commands to exist in order to proceed.
# See README.md
commands=(git ansible rcup)
for cmd in "${commands[@]}"; do
  which $cmd > /dev/null || { echo "ERROR: command not found: ${cmd}" ; exit 1; }
done

# Install ansible roles we depend on
ansible-galaxy install -r provisioning/requirements.yml

if [ -f ~/.dotfilesrc ]; then
  . ~/.dotfilesrc
else
  echo "ERROR: no ~/.dotfilesrc, run ./setup first"
  exit
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function update_vim() {
  echo "Updating vim..."

  if [ ! -f ~/.vim/autoload/plug.vim ]; then
    mkdir -p ~/.vim/autoload
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi

  vim -i NONE -c PlugUpdate -c PlugClean -c qall!
}

# Update dotfiles with rcm
rcup -v

update_vim

sudo ansible-playbook -v provisioning/core.yml

if [ "${DOTFILES_GUI}" == "y" ]; then
  sudo ansible-playbook -v provisioning/desktop.yml
  sudo ansible-playbook -v provisioning/graphic-design.yml
fi

if [ "${DOTFILES_DEV}" == "y"  ]; then
  sudo ansible-playbook -v provisioning/development.yml
fi


