#!/bin/bash
set -e #fail fast

if [ -f ~/.dotfilesrc ]; then
  . ~/.dotfilesrc
else
  echo "ERROR: no ~/.dotfilesrc, run ./setup first"
  exit
fi
sudo apt-get install -y git
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PLATFORM=`uname`

if [[ "$PLATFORM" -eq "Linux" ]]; then
  echo "Setting up linux cli"
  . $DIR/deps_ubuntu_cli
elif [[ "$PLATFORM" -eq "Darwin" ]]; then
  echo "Mac"
  . $DIR/deps_mac_cli
else
  echo "ERROR: Unknown platform"
  exit 1
fi

function update_vim() {
  echo "Updating vim..."

  if [ ! -f ~/.vim/autoload/plug.vim ]; then
    mkdir -p ~/.vim/autoload
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi

  vim -i NONE -c PlugUpdate -c PlugClean -c qall!
}

rcup -v
update_vim

if [ "${DOTFILES_DEV}" == "y"  ]; then
  . $DIR/deps_dev_env
fi

if [ "${DOTFILES_GUI}" == "y" ]; then
  . $DIR/deps_gui
fi

