#!/bin/bash

source ~/.xprofile.local

#export GDK_DPI_SCALE=0.8
xrdb /home/joe/.Xresources
dbus-update-activation-environment DISPLAY XAUTHORITY
xrandr --output DisplayPort-0 --set TearFree on # Enable tearfree on amd gpu
xset s 300
setxkbmap -option caps:escape
exec i3
