#!/bin/bash
export BROWSER=/usr/bin/firefox
export GVFS_DISABLE_FUSE=1

source ~/.xprofile.local

#export GDK_DPI_SCALE=0.8
xrdb /home/joe/.Xresources
dbus-update-activation-environment DISPLAY XAUTHORITY
xrandr --output DisplayPort-0 --set TearFree on # Enable tearfree on amd gpu
xset s 300

setxkbmap -option caps:hyper
xmodmap ~/.Xmodmap # this sets up hyper as the mod switch and configures the third layer
xcape -e 'Mode_switch=Escape' # this makes tapping caps trigger escape

xrdb -merge ~/.Xresources
xrdb -merge ~/.Xresources.local

# Reverse scrolling on lappy
xinput set-prop "DLL0704:01 06CB:76AE Touchpad" "Synaptics Scrolling Distance" -27, -27
eval `ssh-agent | tee ~/.ssh/agent.env`
exec i3
