#!/bin/bash
export BROWSER=/usr/bin/firefox

source ~/.xprofile.local

#export GDK_DPI_SCALE=0.8
xrdb /home/joe/.Xresources
dbus-update-activation-environment DISPLAY XAUTHORITY
xrandr --output DisplayPort-0 --set TearFree on # Enable tearfree on amd gpu
xset s 300
setxkbmap -option caps:escape
# Reverse scrolling on lappy
xinput set-prop "DLL0704:01 06CB:76AE Touchpad" "Synaptics Scrolling Distance" -27, -27
eval `ssh-agent | tee ~/.ssh/agent.env`
exec i3
