#!/bin/bash
# button layouts
#1 - 2
#2 - 3
#3 - 8
#4 - 9

#scroll - AbsWheelUp/Down
#button - 1

#5 - 10
#6 - 11
#7 - 12
#8 - 13

xsetwacom set "Wacom Intuos4 6x9 Pad pad" Button 2 "key +shift =" # Zoom in
# not assigned
# not assigned
xsetwacom set "Wacom Intuos4 6x9 Pad pad" Button 9 "key -" # Zoom out

xsetwacom set "Wacom Intuos4 6x9 Pad pad" Button 10 "key p" # Paintbrush
xsetwacom set "Wacom Intuos4 6x9 Pad pad" Button 11 "key +shift e -" # Eraser
# not assigned
xsetwacom set "Wacom Intuos4 6x9 Pad pad" Button 13 "key +ctrl z -" # undo

xsetwacom set "Wacom Intuos4 6x9 Pad pad" AbsWheelUp "key [" # Increase tool size
xsetwacom set "Wacom Intuos4 6x9 Pad pad" AbsWheelDown "key ]" # Decrease tool size
