# vim: set nospell:
---
- hosts: localhost
  become: true
  connection: local

  tasks:
  - name: Update apt cache if it's more than an hour old
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Update all packages to latest
    apt:
      upgrade: dist

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

  - name: Install packages
    apt:
      name:
        - git
        - htop
        - screen
        - vim
        - ncdu
        - whois
        - openssh-server
        - lzop
        - wakeonlan
        - curl
        - iftop
        - libarchive-tools
        - fdupes
        - ranger
        - multitail
        - iotop-c
        - atool
        - dstat
        - ripgrep

  - name: check if rust/cargo is installed
    become: false
    shell: which cargo
    register: cargo_installed
    ignore_errors: True
    check_mode: False
    changed_when: False

  - name: install "diffr" rust package
    become: false
    when: cargo_installed.rc == 0
    community.general.cargo:
      name: diffr

  roles:
  - role: ansible-role-asdf
    asdf_user: joe
    asdf_version: v0.13.1
    asdf_plugins:
    - name: "ruby"
      versions: ["3.2.2"]
      global: "3.2.2"
    - name: "terraform"
      versions: ["1.2.6", "1.6.2"]
      global: "1.6.2"
    - name: "fzf"
      versions: ["0.43.0"]
    - name: "ripgrep"
      versions: ["13.0.0"]
      global: "13.0.0"


  # For some reason this is giving me a "no such file or directory" error
  # tasks:
  #   - name: install global gems
  #     become: false
  #     ansible.builtin.command:
  #       chdir: ~/code/dotfiles/
  #       cmd: ~/.asdf/shims/bundle update
