# vim: set nospell:
---
- hosts: localhost
  become: true
  connection: local

  tasks:
  - name: Update apt cache if it's more than an hour old
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Update all packages to latest
    apt:
      upgrade: dist

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

  - name: Install packages
    apt:
      name:
        - git
        - htop
        - screen
        - vim
        - ncdu
        - whois
        - openssh-server
        - lzop
        - wakeonlan
        - curl
        - iftop
        - libarchive-tools
        - fdupes
        - ranger
        - multitail
        - iotop-c
        - atool
        - dstat
        - ripgrep
  roles:
  - role: ansible-role-asdf
    asdf_user: joe
    asdf_version: v0.13.1
    asdf_plugins:
    - name: "ruby"
      versions: ["3.2.2"]
      global: "3.2.2"
    - name: "terraform"
      versions: ["1.2.6"]
      global: "1.2.6"
    - name: "fzf"
      versions: ["0.43.0"]
      global: "0.43.0"
