# vim: set nospell:
---
- hosts: localhost
  become: true
  connection: local

  tasks:
  # Update package cache (distro-specific, no generic module for this)
  - name: Update apt cache
    apt:
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_pkg_mgr == "apt"

  # Upgrade all packages (distro-specific)
  - name: Update all packages to latest (apt)
    apt:
      upgrade: dist
    when: ansible_pkg_mgr == "apt"

  - name: Update all packages to latest (dnf)
    dnf:
      name: "*"
      state: latest
    when: ansible_pkg_mgr in ["dnf", "dnf5"]

  # Autoremove (distro-specific)
  - name: Remove dependencies that are no longer required (apt)
    apt:
      autoremove: yes
    when: ansible_pkg_mgr == "apt"

  - name: Remove dependencies that are no longer required (dnf)
    dnf:
      autoremove: yes
    when: ansible_pkg_mgr in ["dnf", "dnf5"]

  # Common packages (same name on all distros)
  - name: Install common packages
    package:
      name:
        - thefuck
        - git
        - htop
        - screen
        - ncdu
        - whois
        - openssh-server
        - lzop
        - curl
        - iftop
        - fdupes
        - ranger
        - multitail
        - atool
        - dstat
        - ripgrep

  # Distro-specific packages (different names)
  - name: Install distro-specific packages (apt)
    apt:
      name:
        - vim
        - wakeonlan
        - libarchive-tools
        - iotop-c
    when: ansible_pkg_mgr == "apt"

  - name: Install distro-specific packages (dnf)
    dnf:
      name:
        - vim-enhanced
        - wol
        - bsdtar
        - iotop
        # Ruby build dependencies
        - perl-FindBin
        - perl-IPC-Cmd
        - perl-File-Compare
        - openssl-devel
        - readline-devel
        - zlib-devel
        - libyaml-devel
        - libffi-devel
    when: ansible_pkg_mgr in ["dnf", "dnf5"]

  - name: check if rust/cargo is installed
    become: false
    shell: which cargo
    register: cargo_installed
    ignore_errors: True
    check_mode: False
    changed_when: False

  - name: install "diffr" rust package
    become: false
    when: cargo_installed.rc == 0
    community.general.cargo:
      name: diffr

- hosts: localhost
  become: false
  connection: local

  tasks:
  - name: Create ~/.local/bin directory
    ansible.builtin.file:
      path: ~/.local/bin
      state: directory
      mode: '0755'

  - name: Download asdf binary
    ansible.builtin.unarchive:
      src: https://github.com/asdf-vm/asdf/releases/download/v0.18.0/asdf-v0.18.0-linux-amd64.tar.gz
      dest: ~/.local/bin
      remote_src: yes
      creates: ~/.local/bin/asdf

  - name: Install asdf plugins
    ansible.builtin.shell: |
      ~/.local/bin/asdf plugin add {{ item }} || true
    args:
      executable: /bin/bash
    loop:
      - ruby
      - terraform
      - fzf
      - ripgrep
    changed_when: false

  - name: Install tool versions
    ansible.builtin.shell: |
      ~/.local/bin/asdf install {{ item.name }} {{ item.version }}
    args:
      executable: /bin/bash
    loop:
      - { name: ruby, version: "3.4.2" }
      - { name: terraform, version: "1.6.2" }
      - { name: fzf, version: "0.63.0" }
      - { name: ripgrep, version: "14.1.1" }
    changed_when: false
