# vim: set nospell:
---
- hosts: localhost
  become: true
  connection: local

  tasks:
  - name: Update apt cache if it's more than an hour old
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Update all packages to latest
    apt:
      upgrade: dist

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

  - name: Install packages
    apt:
      name:
        - git
        - htop
        - screen
        - vim
        - ncdu
        - whois
        - openssh-server
        - lzop
        - wakeonlan
        - curl
        - iftop
        - libarchive-tools
        - fdupes
        - ranger
        - multitail
        - iotop-c
        - atool
        - dstat
        - ripgrep

  - name: check if rust/cargo is installed
    become: false
    shell: which cargo
    register: cargo_installed
    ignore_errors: True
    check_mode: False
    changed_when: False

  - name: install "diffr" rust package
    become: false
    when: cargo_installed.rc == 0
    community.general.cargo:
      name: diffr

- hosts: localhost
  become: false
  connection: local

  tasks:
  - name: Create ~/.local/bin directory
    ansible.builtin.file:
      path: ~/.local/bin
      state: directory
      mode: '0755'

  - name: Download asdf binary
    ansible.builtin.unarchive:
      src: https://github.com/asdf-vm/asdf/releases/download/v0.18.0/asdf-v0.18.0-linux-amd64.tar.gz
      dest: ~/.local/bin
      remote_src: yes
      creates: ~/.local/bin/asdf

  - name: Install asdf plugins
    ansible.builtin.shell: |
      asdf plugin add {{ item }} || true
    args:
      executable: /bin/bash
    loop:
      - ruby
      - terraform
      - fzf
      - ripgrep
    changed_when: false

  - name: Install tool versions
    ansible.builtin.shell: |
      asdf install {{ item.name }} {{ item.version }}
    args:
      executable: /bin/bash
    loop:
      - { name: ruby, version: "3.4.2" }
      - { name: terraform, version: "1.6.2" }
      - { name: fzf, version: "0.63.0" }
      - { name: ripgrep, version: "14.1.1" }
    changed_when: false
