# vim: set nospell:
---
- hosts: localhost
  become: true
  connection: local

  tasks:
  - name: install key for gsuite utils
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: google suite util ppa
    apt_repository:
      repo: deb https://packages.cloud.google.com/apt cloud-sdk main
      state: present

  - name: install key for openscad ppa
    apt_key:
      url: https://files.openscad.org/OBS-Repository-Key.pub
      state: present

  - name: Add solaar ppa
    ansible.builtin.apt_repository:
      repo: ppa:solaar-unifying/stable

  - name: yubico ppa
    apt_repository:
      repo: ppa:yubico/stable
      state: present

  #- name: Install openscad nightly ppa
  #  apt_repository:
  #    repo: deb https://download.opensuse.org/repositories/home:/t-paul/xUbuntu_20.04/ ./
  #    state: present

  - name: Remove unwanted packages
    apt:
      name:
        - notify-osd
        - xautolock
        - xfonts-terminus # this clashes with fonts-terminus
        - mplayer
        - vlc # use mpv now
        - parole # use mpv now
        - compton # use picom now
        - gnome-terminal
      state: absent

  - name: Install packages
    apt:
      state: latest
      name:
        - xfce4-terminal
        - keepassxc
        - feh
        - xss-lock
        - i3-wm
        - i3lock
        - maim
        - xcalib
        # - dispcalgui # This was removed from ubuntu, install seperately below
        - argyll
        - i3status
        - suckless-tools
        - chromium-browser
        - picom
        - fonts-terminus
        - fonts-font-awesome
        - ibus
        - xclip
        - freeglut3
        - trash-cli
        # At one time we also used freerdp-x11
        - freerdp2-x11
        - xbindkeys
        - sshfs
        - hplip
        - xdotool
        - openvpn
        - nvme-cli
        - autofs
        - cifs-utils
        - rofi
        - libx11-dev
        - gcc-avr # for QMK
        - avr-libc # for QMK
        - dfu-programmer # for QMK
        - apt-file
        - arandr
        - nmap
        # - openscad-nightly
        - pasystray
        - rclone
        - awscli
        - filezilla
        - dunst
        - powertop
        - evince # PDF reader, have considered atrill and mupdf as well
        - libglu1-mesa # Needed by prusa-slicer
        - thunar
        - wireguard-tools
        - solaar # Logitech mouse
        - fd-find
        - bat # https://github.com/sharkdp/bat
        - jq
        - sshpass # used by ansible
        - gimp
        - gimp-gmic
        - mpv # video player
        - sxiv # image viewer
        - meshlab # STL viewer
        - fstl # STL viewer
        - ssh-askpass
        - task-spooler
        - fonts-powerline
        - libreoffice-impress
        - libreoffice-writer
        - linssid # wifi scanner
        - network-manager-openvpn
        - network-manager-openvpn-gnome # Needed to configure ovpn
        - ldap-utils
        - mlocate
        - mosh
        - autorandr
        - hugin-tools # photography
        - enfuse # photography
        - imagej # photography
        - xinput-calibrator
        - google-cloud-sdk # Google suite util from ppa
        - ruby
        - python3-gpg # Dropbox dep
        - taskwarrior
        - net-tools
        - recollgui # full text file search
        - newsboat
        - xbacklight
        - x11vnc
        - libimobiledevice-utils # for ios tethering
        - v4l-utils
        - trickle
        - gscan2pdf
        - konwert # can convert files between text encodings
        - peek # screen recording
        - ppa-purge
        - yubikey-manager
        - yubikey-personalization-gui
        - synaptic
        - bluez-tools
        - blueman
        - flatpak
        - fonts-symbola # Unicode symbols - emoji, checkboxes, etc

  - name: Install displayacal flatpak
    community.general.flatpak:
      name: https://dl.flathub.org/repo/appstream/net.displaycal.DisplayCAL.flatpakref
      state: present

  - name: Install nextcloud flatpak
    community.general.flatpak:
      name: https://dl.flathub.org/repo/appstream/com.nextcloud.desktopclient.nextcloud.flatpakref
      state: present
  - name: update flatpaks
    shell:
      cmd: flatpak update --noninteractive
    become: true


  - name: "Populate list of installed packages"
    package_facts:
      manager: "auto"

  - name: Install qrcp
    apt:
      deb: https://github.com/claudiodangelis/qrcp/releases/download/0.8.1/qrcp_0.8.1_linux_x86_64.deb
    when: "'qrcp' not in ansible_facts.packages"

  - name: Install slack
    apt:
      deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.12.0-amd64.deb
    when: "'slack-desktop' not in ansible_facts.packages"

  - name: Install discrod
    apt:
      deb: https://dl.discordapp.net/apps/linux/0.0.16/discord-0.0.16.deb
    when: "'discord' not in ansible_facts.packages"

  - set_fact:
      zoom_version: "{{ ansible_facts.packages['zoom'] | json_query('[].version') }}"
    when: "'zoom' in ansible_facts.packages"

  - name: Print all available facts
    ansible.builtin.debug:
      var: zoom_version

  - name: Install zoom
    apt:
      deb: https://cdn.zoom.us/prod/5.8.0.16/zoom_amd64.deb
    # the zoom_version.0 seems to unpack this from an array (ansible n00b)
    when: "zoom_version is not defined or zoom_version.0 is version_compare('5.8.0.16', '<')"
    # when: "zoom_version is not defined or zoom_version | version_compare('5.8.0.16', '<')"

  # From https://github.com/jitsi/jitsi-meet-electron/releases
  - name: Install jitsi app
    apt:
      deb: https://github.com/jitsi/jitsi-meet-electron/releases/download/v2.8.4/jitsi-meet-amd64.deb
    when: "'jitsi-meet-electron' not in ansible_facts.packages"

  - name: Install Dropbox
    apt:
      deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb
    when: "'dropbox' not in ansible_facts.packages"

  - name: Custom xorg config
    copy:
      dest: /usr/share/X11/xorg.conf.d/99-joe-custom.conf
      src: 99-joe-custom.conf
      owner: root
      group: root

  - name: udev rules
    copy:
      dest: /etc/udev/rules.d/59-sdreader.rules
      src: 59-sdreader.rules
      owner: root
      group: root

  - name: create USB-C dock quirks service
    copy:
      dest: /etc/systemd/system/dock-quirks.service
      src: dock-quirks.service
      owner: root
      group: root

  - name: start USB-C dock quirks
    ansible.builtin.systemd:
      name: dock-quirks
      daemon_reload: yes
      enabled: yes
      state: started
