# vim: set nospell:
---
- hosts: localhost
  become: true
  connection: local

  tasks:
  - name: Install packages
    apt:
      name:
        - feh
        - xautolock
        - i3-wm
        - i3lock
        - maim
        - xcalib
        - i3status
        - suckless-tools
        - chromium-browser
        - compton
        - xfonts-terminus
        - ibus
        - xclip
        - freeglut3
        - trash-cli
        # At one time we also used freerdp-x11
        - freerdp2-x11
        - xbindkeys
        - sshfs
        - hplip
        - xdotool
        - openvpn
        - nvme-cli
        - autofs
        - cifs-utils
        - rofi
        - libx11-dev
        - gcc-avr # for QMK
        - avr-libc # for QMK
        - dfu-programmer # for QMK

  - name: Install slack
    apt:
      deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.3.2-amd64.deb

  - name: Install Dropbox
    apt:
      deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2019.02.14_amd64.deb

  - name: install key for openscad ppa
    apt_key:
      url: https://files.openscad.org/OBS-Repository-Key.pub
      state: present

  - name: Install openscad nightly ppa
    apt_repository:
      repo: deb https://download.opensuse.org/repositories/home:/t-paul/xUbuntu_18.04/ ./
      state: present

  - name: Install openscad-nightly
    apt:
      name:
        - openscad-nightly

  - name: Custom xorg config
    copy:
      dest: /usr/share/X11/xorg.conf.d/99-joe-custom.conf
      src: 99-joe-custom.conf
      owner: root
      group: root
