# vim: set nospell:
---
- hosts: localhost
  become: true
  connection: local

  tasks:
  - name: install key for openscad ppa
    apt_key:
      url: https://files.openscad.org/OBS-Repository-Key.pub
      state: present

  #- name: Install openscad nightly ppa
  #  apt_repository:
  #    repo: deb https://download.opensuse.org/repositories/home:/t-paul/xUbuntu_20.04/ ./
  #    state: present

  - name: Remove unwanted packages
    apt:
      name:
        - notify-osd
        - xautolock
        - xfonts-terminus # this clashes with fonts-terminus
        - mplayer
        - vlc # use mpv now
        - parole # use mpv now
      state: absent

  - name: Install packages
    apt:
      state: latest
      name:
        - keepassxc
        - feh
        - xss-lock
        - i3-wm
        - i3lock
        - maim
        - xcalib
        # - dispcalgui
        - argyll
        - i3status
        - suckless-tools
        - chromium-browser
        - picom
        - fonts-terminus
        - ibus
        - xclip
        - freeglut3
        - trash-cli
        # At one time we also used freerdp-x11
        - freerdp2-x11
        - xbindkeys
        - sshfs
        - hplip
        - xdotool
        - openvpn
        - nvme-cli
        - autofs
        - cifs-utils
        - rofi
        - libx11-dev
        - gcc-avr # for QMK
        - avr-libc # for QMK
        - dfu-programmer # for QMK
        - apt-file
        - arandr
        - nmap
        # - openscad-nightly
        - pasystray
        - rclone
        - awscli
        - filezilla
        - dunst
        - powertop
        - evince # PDF reader, have considered atrill and mupdf as well
        - libglu1-mesa # Needed by prusa-slicer
        - thunar
        - wireguard-tools
        - solaar # Logitech mouse
        - fd-find
        - bat # https://github.com/sharkdp/bat
        - jq
        - sshpass # used by ansible
        - gimp
        - gimp-gmic
        - mpv # video player
        - sxiv # image viewer
        - meshlab # STL viewer
        - ssh-askpass
        - task-spooler
        - fonts-powerline
        - libreoffice-impress

  - name: "Populate list of installed packages"
    package_facts:
      manager: "auto"

  - name: Install slack
    apt:
      deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.12.0-amd64.deb
    when: "'slack-desktop' not in ansible_facts.packages"

  - name: Install Dropbox
    apt:
      deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb
    when: "'dropbox' not in ansible_facts.packages"

  - name: Custom xorg config
    copy:
      dest: /usr/share/X11/xorg.conf.d/99-joe-custom.conf
      src: 99-joe-custom.conf
      owner: root
      group: root

  - name: udev rules
    copy:
      dest: /etc/udev/rules.d/59-sdreader.rules
      src: 59-sdreader.rules
      owner: root
      group: root
