# vim: set nospell:
---
- hosts: localhost
  become: true
  connection: local

  tasks:
  - name: Install packages
    apt:
      name:
        - grip
        - build-essential
        - libssl-dev
        - libreadline-dev
        - zlib1g-dev
        - exuberant-ctags
        - golang-go
        - docker.io
        - libmysqlclient-dev
        - libpq-dev
        - libsqlite3-dev
        - graphviz
        - mariadb-client

  - name: enable docker
    service:
      name: docker
      state: started
      enabled: yes
      masked: false
      #
  # FIXME: have this pull account username from file
  - name: put joe in docker group
    user:
      name: joe
      groups: docker
      append: yes

  - name: Setup asdf-vm
    become: yes
    become_user: joe
    git:
      repo: https://github.com/asdf-vm/asdf.git
      dest: /home/joe/.asdf
      update: yes

  roles:
  - role: ansible-role-asdf
    asdf_user: joe
    asdf_plugins:
      - name: 'ruby'
        versions: ['2.4.9', '2.5.7', '2.6.5', '2.7.0']
        global: '2.7.0'
      - name: 'python'
        versions: ['3.8.2']
        global: '3.8.2'
      - name: 'yarn'
        versions: ['1.22.0']
        global: '1.22.0'
      - name: 'nodejs'
        versions: ['10.19.0']
        global: '10.19.0'
      - name: 'terraform'
        versions: ['0.12.21']
        global: '0.12.21'
      - name: 'golang'
        versions: ['1.14']
        global: '1.14'
      - name: 'ripgrep'
        versions: ['11.0.2']
        global: '11.0.2'
