# vim: set nospell:
---
- hosts: localhost
  become: true
  connection: local

  tasks:
  - name: Install packages
    apt:
      name:
        - grip
        - build-essential
        - libssl-dev
        - libreadline-dev
        - zlib1g-dev
        - exuberant-ctags
        - golang-go
        - docker.io

  - name: enable docker
    service:
      name: docker
      state: started
      enabled: yes
      #
  # FIXME: have this pull account username from file
  - name: put joe in docker group
    user:
      name: joe
      groups: docker
      append: yes
