# vim: set nospell:
---
- hosts: localhost
  become: true
  connection: local

  tasks:
  - name: Install gimp PPA
    apt_repository:
      repo: ppa:ubuntuhandbook1/gimp
      state: present

  - name: Install packages
    apt:
      name:
        - gimp
        - darktable
        # - scribus
        - inkscape
        # - texlive-full
        - exif
        - libmediainfo0v5
        # - rapid-photo-downloader
        - font-manager
        - gmic
        - gimp-plugin-registry
