#!/bin/bash
set -e # fail fast

function update_vim() {
  echo "Updating vim plugins..."

  if [ ! -f ~/.vim/autoload/plug.vim ]; then
    mkdir -p ~/.vim/autoload
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi

  vim -E --not-a-term +PlugUpdate +PlugClean +qall > /dev/null
  #vim -i NONE -c PlugUpdate -c PlugClean -c qall!
}

update_vim
