#!/bin/bash
set -e # fail fast

function update_vim() {
  echo "Updating vim plugins..."

  if [ ! -f ~/.vim/autoload/plug.vim ]; then
    mkdir -p ~/.vim/autoload
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi

  vim --not-a-term +PlugUpdate +PlugClean +qall > /dev/null
  reset -IQ
}

update_vim
