#!/bin/bash
set -e # fail fast

function update_vim() {
  echo "Updating vim plugins..."

  if [ ! -f ~/.vim/autoload/plug.vim ]; then
    mkdir -p ~/.vim/autoload
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi

  # Not clear why, but echoing something to stdin and then sleeping after the
  # reset seems to make this behave and terminate more reliably
  echo "" | vim --not-a-term +PlugUpdate +PlugClean +qall > /dev/null
  reset -IQ
  sleep 1 # let the reset finish?
}

update_vim
